mysql:
  sqlTypeMap:
    bit:
      typeClassification: BOOLEAN
      javaType:
        label: Boolean
        importPath: java.lang.Boolean
    tinyint:
      typeClassification: NUMERIC
      javaType:
        label: Integer
        importPath: java.lang.Integer
    bool:
      typeClassification: BOOLEAN
      javaType:
        label: Boolean
        importPath: java.lang.Boolean
    boolean:
      typeClassification: BOOLEAN
      javaType:
        label: Boolean
        importPath: java.lang.Boolean
    smallint:
      typeClassification: NUMERIC
      javaType:
        label: Integer
        importPath: java.lang.Integer
    mediumint:
      typeClassification: NUMERIC
      javaType:
        label: Integer
        importPath: java.lang.Integer
    int:
      typeClassification: NUMERIC
      javaType:
        label: Integer
        importPath: java.lang.Integer
    integer:
      typeClassification: NUMERIC
      javaType:
        label: Integer
        importPath: java.lang.Integer
    bigint:
      typeClassification: NUMERIC
      javaType:
        label: Long
        importPath: java.lang.Long
    decimal:
      typeClassification: NUMERIC
      javaType:
        label: BigDecimal
        importPath: java.math.BigDecimal
    float:
      typeClassification: NUMERIC
      javaType:
        label: Double
        importPath: java.lang.Double
    double:
      typeClassification: NUMERIC
      javaType:
        label: Double
        importPath: java.lang.Double
    date:
      typeClassification: DATE
      javaType:
        label: LocalDate
        importPath: java.time.LocalDate
    datetime:
      typeClassification: DATETIME
      javaType:
        label: LocalDateTime
        importPath: java.time.LocalDateTime
    timestamp:
      typeClassification: DATETIME
      javaType:
        label: LocalDateTime
        importPath: java.time.LocalDateTime
    time:
      typeClassification: TIME
      javaType:
        label: LocalTime
        importPath: java.time.LocalTime
    char:
      typeClassification: TEXT
      javaType:
        label: String
        importPath: java.lang.String
    varchar:
      typeClassification: TEXT
      javaType:
        label: String
        importPath: java.lang.String
    binary:
      typeClassification: BINARY
      javaType:
        label: byte[]
        importPath:
    varbinary:
      typeClassification: BINARY
      javaType:
        label: byte[]
        importPath:
    tinyblob:
      typeClassification: BINARY
      javaType:
        label: byte[]
        importPath:
    blob:
      typeClassification: BINARY
      javaType:
        label: byte[]
        importPath:
    mediumblob:
      typeClassification: BINARY
      javaType:
        label: byte[]
        importPath:
    longblob:
      typeClassification: BINARY
      javaType:
        label: byte[]
        importPath:
    enum:
      typeClassification: ENUM
      javaType:
        label: Object
        importPath:
    set:
      typeClassification: SET
      javaType:
        label: Object
        importPath:
