spring.profiles.include:
  - 'mysql'
  - 'validation'
  - 'gui'
  - 'springinitializr'
  - 'filenaming'

zip-file:
  tempDir: temp

file-naming-dependencies:
  templateTypeTemplateKeyMap:
    REPOSITORY: ENTITY
    SERVICE: ENTITY
    ENTITY: ENTITY
    DTO: ENTITY
    CREATE_REQUEST: ENTITY
    UPDATE_REQUEST: ENTITY
    REQUEST_MAPPER: ENTITY
    RESPONSE_MAPPER: ENTITY
    NOT_FOUND_EXCEPTION: NONE
    CONTROLLER_ADVICE: NONE
    CONTROLLER: ENTITY
    CONFIGURATION: NONE
    PROPERTIES: NONE
    ENUM: ENTITY

template:
  templatesRelativePath: templates
  templateExtension: vm
  templateTypeDynamicPlaceholder: template-type

  templateKeyToNameMap:
    ENTITY: entity
    ENTITY_CAPITALIZED: Entity
    ENTITY_ID_TYPE: entity-id-type
    IMPORT: template-type-import
    PACKAGE: template-type-package
    CLASS_NAME: template-type-class
    SQL_TABLE: sql-table
    DATASOURCE_URL: datasource-url
    DATASOURCE_USERNAME: datasource-username
    DATASOURCE_PASSWORD: datasource-password
    DATASOURCE_DRIVER: datasource-driver
    SERVER_PORT: server-port
    ENUM_VALUES: enum-values

  templateTypeToTemplateFileNameMap:
    REPOSITORY: repository
    SERVICE: service
    ENTITY: entity
    DTO: dto
    CREATE_REQUEST: createRequest
    UPDATE_REQUEST: updateRequest
    REQUEST_MAPPER: requestMapper
    RESPONSE_MAPPER: responseMapper
    NOT_FOUND_EXCEPTION: not-found-exception
    CONTROLLER_ADVICE: controllerAdvice
    CONTROLLER: controller
    CONFIGURATION: config
    PROPERTIES: properties
    ENUM: enum

template-type-labels:
  templateTypeToLabelMap:
    REPOSITORY: repository
    SERVICE: service
    ENTITY: entity
    DTO: dto
    CREATE_REQUEST: create-request
    UPDATE_REQUEST: update-request
    REQUEST_MAPPER: request-mapper
    RESPONSE_MAPPER: response-mapper
    NOT_FOUND_EXCEPTION: exception
    CONTROLLER_ADVICE: controller-advice
    CONTROLLER: controller
    CONFIGURATION: config
    PROPERTIES: application
    ENUM: enum

automation-build:
  mavenDependencies:
    -
      >
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.9.2</version>
          </dependency>
    -
      >
        <dependency>
          <groupId>io.springfox</groupId>
          <artifactId>springfox-swagger-ui</artifactId>
          <version>2.9.2</version>
        </dependency>
  gradleDependencies:
    - "compile group: 'io.springfox', name: 'springfox-swagger2', version: '2.9.2'"
    - "compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.0.2'"

spring-initializr:
  springBootVersion: 2.1.5.RELEASE
  dependencies:
    - data-jpa
    - web
    - lombok
  sqlDialectToDependencyMap:
    MY_SQL: mysql





