mysql:
  sqlTypeMap:
    bit:
      typeClassification: BOOLEAN
      javaType: BOOLEAN
    tinyint:
      typeClassification: NUMERIC
      javaType: INTEGER
    bool:
      typeClassification: BOOLEAN
      javaType: BOOLEAN
    boolean:
      typeClassification: BOOLEAN
      javaType: BOOLEAN
    smallint:
      typeClassification: NUMERIC
      javaType: INTEGER
    mediumint:
      typeClassification: NUMERIC
      javaType: INTEGER
    int:
      typeClassification: NUMERIC
      javaType: INTEGER
    integer:
      typeClassification: NUMERIC
      javaType: INTEGER
    bigint:
      typeClassification: NUMERIC
      javaType: LONG
    decimal:
      typeClassification: NUMERIC
      javaType: BIG_DECIMAL
    float:
      typeClassification: NUMERIC
      javaType: DOUBLE
    double:
      typeClassification: NUMERIC
      javaType: DOUBLE
    date:
      typeClassification: DATE
      javaType: LOCAL_DATE
    datetime:
      typeClassification: DATETIME
      javaType: LOCAL_DATE_TIME
    timestamp:
      typeClassification: DATETIME
      javaType: LOCAL_DATE_TIME
    time:
      typeClassification: TIME
      javaType: LOCAL_TIME
    char:
      typeClassification: TEXT
      javaType: STRING
    varchar:
      typeClassification: TEXT
      javaType: STRING
    binary:
      typeClassification: BINARY
      javaType: BYTE_ARR
    varbinary:
      typeClassification: BINARY
      javaType: BYTE_ARR
    tinyblob:
      typeClassification: BINARY
      javaType: BYTE_ARR
    blob:
      typeClassification: BINARY
      javaType: BYTE_ARR
    mediumblob:
      typeClassification: BINARY
      javaType: BYTE_ARR
    longblob:
      typeClassification: BINARY
      javaType: BYTE_ARR
    enum:
      typeClassification: ENUM
      javaType: OBJECT
    set:
      typeClassification: SET
      javaType: OBJECT
