spring.profiles.include:
  - 'mysql'
  - 'validation'

file-extension:
  typeToFileExtensionMap:
    REPOSITORY: java
    SERVICE: java
    ENTITY: java
    DTO: java
    CREATE_REQUEST: java
    UPDATE_REQUEST: java
    REQUEST_MAPPER: java
    RESPONSE_MAPPER: java
    EXCEPTION: java
    CONTROLLER_ADVICE: java
    CONTROLLER: java
    CONFIGURATION: java

file-naming-dependencies:
  templateTypeTemplateKeyMap:
    REPOSITORY: ENTITY
    SERVICE: ENTITY
    ENTITY: ENTITY
    DTO: ENTITY
    CREATE_REQUEST: ENTITY
    UPDATE_REQUEST: ENTITY
    REQUEST_MAPPER: ENTITY
    RESPONSE_MAPPER: ENTITY
    EXCEPTION: NONE
    CONTROLLER_ADVICE: NONE
    CONTROLLER: ENTITY
    CONFIGURATION: NONE

file-suffix:
  typeToSuffixMap:
    REPOSITORY: Repository
    SERVICE: Service
    ENTITY:
    DTO: Dto
    CREATE_REQUEST: CreateRequest
    UPDATE_REQUEST: UpdateRequest
    REQUEST_MAPPER: RequestMapper
    RESPONSE_MAPPER: ResponceMapper
    EXCEPTION: ResourceNotFoundException
    CONTROLLER_ADVICE: ResourceExceptionHandler
    CONTROLLER: Controller
    CONFIGURATION: AppConfig

package-naming:
  default-project-path: src.main.java
  custom-package-separator: .

  typeToPackageNameMap:
    REPOSITORY: repository
    SERVICE: service
    ENTITY: domain
    DTO: domain.dto.response
    CREATE_REQUEST:  domain.dto.request
    UPDATE_REQUEST:  domain.dto.request
    REQUEST_MAPPER:  mapper.request
    RESPONSE_MAPPER:  mapper.response
    EXCEPTION: exception
    CONTROLLER_ADVICE: controller.advice
    CONTROLLER: controller
    CONFIGURATION: config

template:
  templatesRelativePath: templates
  templateExtension: vm
  templateTypeDynamicPlaceholder: template-type

  templateKeyToNameMap:
    ENTITY: entity
    ENTITY_CAPITALIZED: Entity
    ENTITY_ID_TYPE: entity-id-type
    IMPORT: ${templateTypeDynamicPlaceholder}-import
    PACKAGE: ${templateTypeDynamicPlaceholder}-package
    CLASS_NAME: ${templateTypeDynamicPlaceholder}-class
    SQL_TABLE: sql-table

  templateTypeToFileNameMap:
    REPOSITORY: repository
    SERVICE: service
    ENTITY: entity
    DTO: dto
    CREATE_REQUEST: createRequest
    UPDATE_REQUEST: updateRequest
    REQUEST_MAPPER: requestMappet
    RESPONSE_MAPPER: responseMapper
    EXCEPTION: exception
    CONTROLLER_ADVICE: conrollerAdvice
    CONTROLLER: controller
    CONFIGURATION: config

template-type-labels:
  templateTypeToLabelMap:
    REPOSITORY: repository
    SERVICE: service
    ENTITY: entity
    DTO: dto
    CREATE_REQUEST: create-request
    UPDATE_REQUEST: update-request
    REQUEST_MAPPER: request-mapper
    RESPONSE_MAPPER: response-mapper
    EXCEPTION: exception
    CONTROLLER_ADVICE: controller-advice
    CONTROLLER: controller
    CONFIGURATION: config