validation:
  annotations:
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh
  -
    label: lol
    supportedTypes:
      - loh
    parameterList:
      -
        label: loh
        type: loh


