package tk.roydgar.restinitializr.model.enums.template;

public enum TemplateKey {
    ENTITY,
    ENTITY_CAPITALIZED,
    ENTITY_ID_TYPE,
    IMPORT,
    PACKAGE,
    CLASS_NAME,
    SQL_TABLE,
    DATASOURCE_DIALECT,
    DATASOURCE_PORT,
    DATASOURCE_HOST,
    DATASOURCE_DB_NAME,
    DATASOURCE_USE_UNICODE,
    DATASOURCE_SERVER_TIMEZONE,
    DATASOURCE_CREATE_TABLE_IF_NOT_EXIST,
    DATASOURCE_USERNAME,
    DATASOURCE_PASSWORD,
    DATASOURCE_DRIVER,
    SERVER_PORT,
    ENUM_VALUES,
    NONE
}
